### ISSUE TITLE
Not able to use with docker?

### ISSUE THREAD

**Issue by gwsampso** [teddziuba/django-sslserver#86]
I have a django project which successfully runs in a docker container, using docker-compose.

I install django-sslserver locally, test it works.

I add django-sslserver to my requirements, change the run command in my docker-compose to the modified `runsslserver 0.0.0.0:8000` then run docker-compose up --build.

I navigate to the site, no load.

Has anybody got django-sslserver running in a container?

**Comment by gwsampso** [comment]
Bump

**Comment by junaiid-khattak** [comment]
@gwsampso any luck?

**Comment by wilomgfx** [comment]
It works for me

**Comment by eddyLazar** [comment]
works for me either

**Comment by gwsampso** [comment]
@wilomgfx or @eddyLazar would you be willing to share your Dockerfile and docker-compose.yml to help me

**Comment by eddyLazar** [comment]
I really didn't do anything special 

this is part of docker-compose
```
web:
    build: .
    command: bash -c "python manage.py runsslserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
```

then just go to `localhost:8000`, and you need
